/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAO.graphics;

import DAO.implementation.GestionConge;
import static com.sun.jmx.trace.Trace.isSelected;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import entites.Conge;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.text.MessageFormat;
import static java.util.Collections.list;
import java.util.HashMap;
import java.util.List;
import java.awt.print.*;
import java.text.*;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import technique.MyConnexion;

/**
 *
 * @author Foued ben brahim
 */
public class GestionDeConge extends javax.swing.JFrame {
    
private Connection Connection;

   
    /**
     * Creates new form GestionDeConge
     */
    public GestionDeConge() {
         Connection=MyConnexion.getInstance();
        initComponents();
        LAbel_id_supp.setVisible(false);
        id_conge_supp.setVisible(false);
        confirmerbutt.setVisible(false);
        jLabelmail.setVisible(false);
        Email.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jcombo_Rep = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        id_conge_supp = new javax.swing.JTextField();
        LAbel_id_supp = new javax.swing.JLabel();
        confirmerbutt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonPrint = new javax.swing.JButton();
        jLabelmail = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rep_dec = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NOM = new javax.swing.JTextField();
        Fonction = new javax.swing.JTextField();
        date_deb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        date_ded_dec = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        date_fin = new javax.swing.JTextField();
        date_fin_dec = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rep = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1350, 750));
        setMinimumSize(new java.awt.Dimension(1350, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/imprimer-icone-6120-64.png"))); // NOI18N
        jButton3.setText("Imprimer la liste ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable7.setBackground(new java.awt.Color(51, 153, 255));
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable7MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable7);

        jcombo_Rep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sans reponse", "accepte", "refuse" }));
        jcombo_Rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombo_RepActionPerformed(evt);
            }
        });

        jLabel14.setText("Selectionner : conge accepte/refuse/sans reponse : ");

        jLabel15.setText("LISTE DE DEMANDES");

        jButton4.setText("Envoi Reponse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/erase.png"))); // NOI18N
        jButton5.setText("Supprimer Demande");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        LAbel_id_supp.setText("ID conge");

        confirmerbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verifier-ok-oui-icone-5200-64.png"))); // NOI18N
        confirmerbutt.setText("Confirmer la suppression");
        confirmerbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(795, 795, 795)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jcombo_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LAbel_id_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_conge_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmerbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcombo_Rep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_conge_supp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LAbel_id_supp))
                        .addGap(26, 26, 26)
                        .addComponent(confirmerbutt)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulter les demandes", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jTable2.setModel(new DAO.graphics.TableCongeAccepte());
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setText("CONGES ACCEPTE");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fleche-recycler-recharger-faire-pivoter-icone-4482-64.png"))); // NOI18N
        jButton6.setText("Actualise");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10-icone-5431-64.png"))); // NOI18N
        jButton7.setText("Envoyer un email ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/imprimer-icone-6120-64.png"))); // NOI18N
        jButtonPrint.setText("Imprimer");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jLabelmail.setText("Adresse Email : ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonPrint)
                        .addGap(60, 60, 60)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Email)))
                        .addGap(133, 133, 133))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButtonPrint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelmail)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Suivi Conge", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setText("nom");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(122, 89, 60, 14);

        jLabel4.setText("Fonction");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(122, 127, 110, 14);

        jLabel5.setText("Date deb conge");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(122, 158, 120, 14);

        jLabel6.setText("Reponse");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(122, 286, 100, 27);

        rep_dec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "accepte", "non accepte" }));
        rep_dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep_decActionPerformed(evt);
            }
        });
        jPanel2.add(rep_dec);
        rep_dec.setBounds(273, 326, 100, 20);

        jTable4.setModel(new DAO.graphics.TableCongeSansRep());
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(410, 20, 390, 140);

        jLabel8.setText("ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(122, 24, 60, 14);

        ID.setEditable(false);
        jPanel2.add(ID);
        ID.setBounds(276, 21, 90, 20);

        NOM.setEditable(false);
        jPanel2.add(NOM);
        NOM.setBounds(276, 86, 90, 20);

        Fonction.setEditable(false);
        jPanel2.add(Fonction);
        Fonction.setBounds(276, 124, 90, 20);

        date_deb.setEditable(false);
        jPanel2.add(date_deb);
        date_deb.setBounds(276, 155, 90, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verifier-ok-oui-icone-5200-64.png"))); // NOI18N
        jButton2.setText(" Reponse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(490, 220, 140, 41);

        date_ded_dec.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1423947177902L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jPanel2.add(date_ded_dec);
        date_ded_dec.setBounds(276, 186, 100, 30);

        jLabel10.setText("decision Date deb conge *");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(122, 189, 140, 14);

        date_fin.setEditable(false);
        jPanel2.add(date_fin);
        date_fin.setBounds(273, 224, 100, 20);

        date_fin_dec.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1423947177902L), null, null, java.util.Calendar.DAY_OF_MONTH));
        jPanel2.add(date_fin_dec);
        date_fin_dec.setBounds(273, 255, 100, 30);

        jLabel11.setText("Date fin conge");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(122, 227, 130, 14);

        jLabel12.setText("decision Date fin conge * ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(122, 258, 140, 14);

        rep.setEditable(false);
        jPanel2.add(rep);
        rep.setBounds(273, 289, 100, 20);

        jLabel9.setText("Decision");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(122, 323, 110, 27);

        Cin.setEditable(false);
        jPanel2.add(Cin);
        Cin.setBounds(276, 52, 90, 20);

        jLabel13.setText("Cin");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(122, 55, 60, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10-icone-5431-64.png"))); // NOI18N
        jButton1.setText("Envoyer la reponse par email");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(490, 270, 230, 50);

        jTabbedPane1.addTab("gerer les demandes", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(320, 120, 810, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1350, 750));
        jLabel7.setMinimumSize(new java.awt.Dimension(1350, 750));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1360, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rep_decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep_decActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rep_decActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
 int row = jTable4.getSelectedRow();
      String table_click0 = jTable4.getModel().getValueAt(row, 0).toString();
      ID.setText(table_click0);
      String table_click1 = jTable4.getModel().getValueAt(row, 1).toString();
      Cin.setText(table_click1);
      String table_click2 = jTable4.getModel().getValueAt(row, 2).toString();
      NOM.setText(table_click2); 
      String table_click3 = jTable4.getModel().getValueAt(row, 3).toString();
      Fonction.setText(table_click3);
      String table_click4 = jTable4.getModel().getValueAt(row, 4).toString();
      date_deb.setText(table_click4);
      String table_click5 = jTable4.getModel().getValueAt(row, 5).toString();
      date_fin.setText(table_click5);
      String table_click6 = jTable4.getModel().getValueAt(row, 6).toString();
      rep.setText(table_click6);
      
      
      
        
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
       
    int ID1 =Integer.parseInt(ID.getText());
   
            
            String date_deb1 = date_ded_dec.getValue().toString();
        String date_fin1= date_fin_dec.getValue().toString();
        String rep=rep_dec.getSelectedItem().toString();

        Conge emp = new Conge();
        
      
        emp.setId_conge(ID1);
        emp.setDate_deb_conge(date_deb1);
        emp.setDate_fin_conge(date_fin1);
        emp.setRep_directeur(rep);

        GestionConge empDAO = new GestionConge();
        empDAO.Reponse_conge(emp);
        JOptionPane.showMessageDialog(rootPane, "Reponse enregistre"); // message d'alert
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcombo_RepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombo_RepActionPerformed

        String x = jcombo_Rep.getSelectedItem().toString();
        if (x=="sans reponse")
        { jLabel15.setText("LISTE DES DEMANDES SANS REPONSE");
            jTable7 = new javax.swing.JTable();

            jTable7.setModel(new DAO.graphics.TableCongeSansRep());

            jScrollPane7.setViewportView(jTable7);

        }
        if (x=="accepte")
        { jLabel15.setText("LISTE DES DEMANDES ACCEPTE");
            jTable7 = new javax.swing.JTable();

            jTable7.setModel(new DAO.graphics.TableCongeAccepte());

            jScrollPane7.setViewportView(jTable7);
        }
        if (x=="refuse")
        {  jLabel15.setText("LISTE DES DEMANDES REFUSE");
            jTable7 = new javax.swing.JTable();

            jTable7.setModel(new DAO.graphics.TableCongeRefuse());

            jScrollPane7.setViewportView(jTable7);
        }

    }//GEN-LAST:event_jcombo_RepActionPerformed

    private void jTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MouseClicked

        
        
		
		
	
    }//GEN-LAST:event_jTable7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        try {
//            // - Connexion à la base
//       // Connection conn=Connection.getInstance();
//            // - Chargement et compilation du rapport (charger le fichier jrxml déjà généré)
//            JasperDesign jasperDesign = JRXmlLoader.load("E:\\3A\\SEMESTRE 2\\PIDEV\\TP\\HeraHopital\\src\\Reports\\ListeConge.jasper");
//            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
//            // - Paramètres à envoyer au rapport
//            Map  parameters = new HashMap();
//            parameters.put("Titre", "Titre");
//            // - Execution du rapport
//            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, Connection);
//            // - Création du rapport au format PDF
//            JasperExportManager.exportReportToPdfFile(jasperPrint, "E:\\3A\\SEMESTRE 2\\PIDEV\\TP\\HeraHopital\\src\\Reports\\ListeConge.pdf");
//            JOptionPane.showMessageDialog( this, "Fichier exporté avec succes !");
//        }
//
//        catch (JRException e) {
//            JOptionPane.showMessageDialog( this, "Erreur lors de l'export !"+e.getMessage());
//         }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 LAbel_id_supp.setVisible(true);
id_conge_supp.setVisible(true);
confirmerbutt.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void confirmerbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerbuttActionPerformed
          JOptionPane.showConfirmDialog(rootPane, "Etes vous sure de vouloir supprimer l'absence de Mr " + jTable7.getValueAt(jTable7.getSelectedRow(), 1) + "?", "",  JOptionPane.OK_CANCEL_OPTION);
 
    int ID =Integer.parseInt(id_conge_supp.getText());

        Conge emp = new Conge();
        
      
        
        emp.setId_conge(ID);

        GestionConge empDAO = new GestionConge();
        empDAO.SupprimerDemandeConge(emp);
//Afficher un message de confirmation
        JOptionPane.showMessageDialog(this, "Suppression effectué avec succès");

    }//GEN-LAST:event_confirmerbuttActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jTable2 = new javax.swing.JTable();

            jTable2.setModel(new DAO.graphics.TableCongeAccepte());

            jScrollPane2.setViewportView(jTable2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       EnvoiMail E = new EnvoiMail();
       E.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         EnvoiMail E = new EnvoiMail();
       E.setVisible(true);
       this.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
       MessageFormat header = new MessageFormat("Report print");
        MessageFormat footer = new MessageFormat("page");
        
        try {
            jTable2.print(JTable.PrintMode.NORMAL,header,footer);
        } catch (PrinterException ex) {
            Logger.getLogger(GestionDeConge.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
 Email.setVisible(true);
 jLabelmail.setVisible(true);
        int row = jTable2.getSelectedRow();
        String table_click = jTable2.getModel().getValueAt(row, 7).toString();
        
        Email.setText(table_click);        
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeConge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeConge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeConge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeConge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeConge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cin;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fonction;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel LAbel_id_supp;
    private javax.swing.JTextField NOM;
    private javax.swing.JButton confirmerbutt;
    private javax.swing.JTextField date_deb;
    private javax.swing.JSpinner date_ded_dec;
    private javax.swing.JTextField date_fin;
    private javax.swing.JSpinner date_fin_dec;
    private javax.swing.JTextField id_conge_supp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable7;
    private javax.swing.JComboBox jcombo_Rep;
    private javax.swing.JTextField rep;
    private javax.swing.JComboBox rep_dec;
    // End of variables declaration//GEN-END:variables
}
