/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAO.graphics;

import DAO.implementation.DAO_utlisateur;
import DAO.implementation.GestionDeEmploiDuTemps;
import entites.Emploi;
import entites.Medecin;
import entites.stagiaire;
import entites.utilisateur;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Foued ben brahim
 */
public class GestionDeEmploi extends javax.swing.JFrame {

    /**
     * Creates new form GestionDeEmploi
     */
    public GestionDeEmploi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        dt_deb_sem1 = new javax.swing.JSpinner();
        merc1 = new javax.swing.JTextField();
        dt_fin_sem1 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        lund1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        vend1 = new javax.swing.JTextField();
        mard1 = new javax.swing.JTextField();
        jeud1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        VendS1 = new javax.swing.JTextField();
        jeudS1 = new javax.swing.JTextField();
        MercS1 = new javax.swing.JTextField();
        mardS1 = new javax.swing.JTextField();
        ludS1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        AjouterEmploi1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dim1 = new javax.swing.JTextField();
        sam1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        dimS1 = new javax.swing.JTextField();
        SamS1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        nom_sal = new javax.swing.JTextField();
        date_deb_txt = new javax.swing.JTextField();
        date_fin_txt = new javax.swing.JTextField();
        Id_emploi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Type_sal2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dt_deb_sem = new javax.swing.JSpinner();
        merc = new javax.swing.JTextField();
        dt_fin_sem = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        lund = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        vend = new javax.swing.JTextField();
        mard = new javax.swing.JTextField();
        jeud = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        VendS = new javax.swing.JTextField();
        jeudS = new javax.swing.JTextField();
        MercS = new javax.swing.JTextField();
        mardS = new javax.swing.JTextField();
        ludS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AjouterEmploi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dim = new javax.swing.JTextField();
        sam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dimS = new javax.swing.JTextField();
        SamS = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        type_sal1 = new javax.swing.JTextField();
        cin_s = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        nom_sal2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 650));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1239, 902, 0, 0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1239, 955, 100, 100);

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1350, 750));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1350, 559));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        dt_deb_sem1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1581322200000L), java.util.Calendar.DAY_OF_MONTH));

        merc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merc1ActionPerformed(evt);
            }
        });

        dt_fin_sem1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1581322200000L), java.util.Calendar.DAY_OF_MONTH));

        jLabel16.setText("Date de debut du semaine");

        lund1.setName(""); // NOI18N
        lund1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lund1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Date de la fin du semaine");

        vend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vend1ActionPerformed(evt);
            }
        });

        mard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mard1ActionPerformed(evt);
            }
        });

        jeud1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeud1ActionPerformed(evt);
            }
        });

        jButton3.setText("Envoyer l'emploi par email");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Imprimer");

        VendS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendS1ActionPerformed(evt);
            }
        });

        jeudS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeudS1ActionPerformed(evt);
            }
        });

        MercS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercS1ActionPerformed(evt);
            }
        });

        mardS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mardS1ActionPerformed(evt);
            }
        });

        ludS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ludS1ActionPerformed(evt);
            }
        });

        jLabel18.setText("ID emlpoi");

        jLabel19.setText("MARDI");

        jLabel21.setText("LUNDI");

        jLabel22.setText("16H - 00H");

        jLabel23.setText("VENDREDI");

        AjouterEmploi1.setText("Modifier Emploi");
        AjouterEmploi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEmploi1ActionPerformed(evt);
            }
        });

        jLabel24.setText("JEUDI");

        jLabel26.setText("MERCREDI");

        jLabel27.setText("8H - 16H");

        dim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dim1ActionPerformed(evt);
            }
        });

        sam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sam1ActionPerformed(evt);
            }
        });

        jLabel28.setText("SAMEDI");

        jLabel29.setText("DIMANCHE");

        dimS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimS1ActionPerformed(evt);
            }
        });

        SamS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamS1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Nom salarier");

        date_deb_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_deb_txtActionPerformed(evt);
            }
        });

        date_fin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_fin_txtActionPerformed(evt);
            }
        });

        jTable3.setModel(new DAO.graphics.TableEmploi());
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton1.setText("Supprimer Emploi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel33.setText("Type salarier");

        jButton2.setText("Actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(514, 514, 514)
                                .addComponent(jLabel23))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(29, 29, 29)
                                .addComponent(ludS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(mardS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(MercS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jeudS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(VendS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(SamS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dimS1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(35, 35, 35)
                                .addComponent(lund1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(mard1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(merc1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jeud1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vend1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(sam1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dim1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel21)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel19)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel26)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel24)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel28)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel29))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(nom_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(34, 34, 34)
                                .addComponent(Id_emploi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(Type_sal2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_fin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dt_deb_sem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(date_deb_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dt_fin_sem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButton3)
                .addGap(41, 41, 41)
                .addComponent(AjouterEmploi1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(Id_emploi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(date_deb_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(nom_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Type_sal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel17)
                                    .addComponent(date_fin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(dt_deb_sem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_fin_sem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel29)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mard1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jeud1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lund1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vend1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(merc1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sam1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dim1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mardS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jeudS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ludS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VendS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MercS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SamS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dimS1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterEmploi1)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("modifier ou supprimer un emploi", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dt_deb_sem.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1581322200000L), java.util.Calendar.DAY_OF_MONTH));
        jPanel2.add(dt_deb_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        merc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercActionPerformed(evt);
            }
        });
        jPanel2.add(merc, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 340, 99, 48));

        dt_fin_sem.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1581322200000L), java.util.Calendar.DAY_OF_MONTH));
        jPanel2.add(dt_fin_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        jLabel13.setText("Date de debut du semaine");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        lund.setName(""); // NOI18N
        lund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lundActionPerformed(evt);
            }
        });
        jPanel2.add(lund, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 340, 99, 48));

        jLabel14.setText("Date de la fin du semaine");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        vend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendActionPerformed(evt);
            }
        });
        jPanel2.add(vend, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 340, 99, 48));

        mard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mardActionPerformed(evt);
            }
        });
        jPanel2.add(mard, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 340, 99, 48));

        jeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeudActionPerformed(evt);
            }
        });
        jPanel2.add(jeud, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 99, 48));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 406, 930, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 923, 16));

        VendS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendSActionPerformed(evt);
            }
        });
        jPanel2.add(VendS, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 427, 99, 48));

        jeudS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeudSActionPerformed(evt);
            }
        });
        jPanel2.add(jeudS, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 427, 99, 48));

        MercS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercSActionPerformed(evt);
            }
        });
        jPanel2.add(MercS, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 427, 99, 48));

        mardS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mardSActionPerformed(evt);
            }
        });
        jPanel2.add(mardS, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 427, 99, 48));

        ludS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ludSActionPerformed(evt);
            }
        });
        jPanel2.add(ludS, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 427, 99, 48));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel2.setText("MARDI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 265, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel1.setText("LUNDI");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 265, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("16H - 00H");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 427, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("VENDREDI");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 265, -1, -1));

        AjouterEmploi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verifier-ok-oui-icone-5200-64.png"))); // NOI18N
        AjouterEmploi.setText("Ajout Emploi");
        AjouterEmploi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEmploiActionPerformed(evt);
            }
        });
        jPanel2.add(AjouterEmploi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("JEUDI");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 265, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("MERCREDI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("8H - 16H");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 327, 60, -1));

        dim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimActionPerformed(evt);
            }
        });
        jPanel2.add(dim, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 340, 99, 48));

        sam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samActionPerformed(evt);
            }
        });
        jPanel2.add(sam, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 340, 99, 48));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("SAMEDI");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 265, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("DIMANCHE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 265, 90, -1));

        dimS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimSActionPerformed(evt);
            }
        });
        jPanel2.add(dimS, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 427, 99, 48));

        SamS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamSActionPerformed(evt);
            }
        });
        jPanel2.add(SamS, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 427, 99, 48));

        jLabel15.setText(".");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 184, 21, -1));

        jTable2.setModel(new DAO.graphics.TableSalarierNonPaye());
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 310, 180));

        jButton5.setText("actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel30.setText("Type salarier");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel31.setText("nom salarier");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        jPanel2.add(type_sal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, -1));

        cin_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cin_sActionPerformed(evt);
            }
        });
        jPanel2.add(cin_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 150, -1));

        jLabel32.setText("CIN salarier");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        jPanel2.add(nom_sal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/10-icone-5431-64.png"))); // NOI18N
        jButton6.setText("Envoyer les emplois par email");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, 40));

        jTabbedPane1.addTab("ajouter un emploi du temps", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(300, 130, 980, 570);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/back.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(1350, 750));
        jLabel10.setMinimumSize(new java.awt.Dimension(1350, 750));
        jLabel10.setPreferredSize(new java.awt.Dimension(1350, 750));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1350, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SamSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SamSActionPerformed

    private void dimSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimSActionPerformed

    private void samActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samActionPerformed

    private void dimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimActionPerformed

    private void AjouterEmploiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEmploiActionPerformed

        String  nom_user = nom_sal2.getText();
        String date_deb_sem = dt_deb_sem.getValue().toString();
        String date_fin_sem = dt_fin_sem.getValue().toString();
        String type_user = type_sal1.getText();
        String lundi = lund.getText();
        String mardi = mard.getText();
        String mercredi = merc.getText();
        String jeudi = jeud.getText();
        String vendredi = vend.getText();
        String samedi = sam.getText();
        String dimanche = dim.getText();
        String lundiSoire = ludS.getText();
        String mardiSoire = mardS.getText();
        String mercrediSoire = MercS.getText();
        String jeudiSoire = jeudS.getText();
        String vendrediSoire = VendS.getText();
        String samediSoire = SamS.getText();
        String dimancheSoire = dimS.getText();

        Emploi emp = new Emploi();
        emp.setNom_user(nom_user);
        emp.setDate_deb_sem(date_deb_sem);
        emp.setDate_fin_sem(date_fin_sem);
        emp.setType_user(type_user);
        emp.setDimanche(dimanche);
        emp.getDimancheSoire();
        emp.setJeudi(jeudi);
        emp.setJeudiSoire(jeudiSoire);
        emp.setLundi(lundi);
        emp.setLundiSoire(lundiSoire);
        emp.setMardi(mardi);
        emp.setMardiSoire(mardiSoire);
        emp.setMercredi(mercredi);
        emp.setMercrediSoire(mercrediSoire);
        emp.setSamedi(samedi);
        emp.setSamediSoire(samediSoire);
        emp.setVendredi(vendredi);
        emp.setVendrediSoire(vendrediSoire);
        emp.setDimancheSoire(dimancheSoire);

        GestionDeEmploiDuTemps empDAO = new GestionDeEmploiDuTemps();
        empDAO.Ajouteremploi(emp);
        JOptionPane.showMessageDialog(rootPane, "ajout effectueé"); // message d'alert
    }//GEN-LAST:event_AjouterEmploiActionPerformed

    private void ludSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ludSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ludSActionPerformed

    private void mardSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mardSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mardSActionPerformed

    private void MercSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MercSActionPerformed

    private void jeudSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeudSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeudSActionPerformed

    private void VendSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendSActionPerformed

    private void jeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeudActionPerformed

    private void mardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mardActionPerformed

    private void vendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendActionPerformed

    private void lundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lundActionPerformed

    private void mercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mercActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        String table_click = jTable2.getModel().getValueAt(row, 0).toString();
        nom_sal2.setText(table_click);
        String table_click2 = jTable2.getModel().getValueAt(row, 1).toString();
        cin_s.setText(table_click2);
        String table_click3 = jTable2.getModel().getValueAt(row, 2).toString();
        type_sal1.setText(table_click3);
      
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        initComponents();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cin_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cin_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cin_sActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int row = jTable3.getSelectedRow();
        String table_click = jTable3.getModel().getValueAt(row, 0).toString();
        Id_emploi.setText(table_click);
        String table_click2 = jTable3.getModel().getValueAt(row, 1).toString();
        nom_sal.setText(table_click2);

        String table_click4 = jTable3.getModel().getValueAt(row, 2).toString();
        date_deb_txt.setText(table_click4);
        String table_click5 = jTable3.getModel().getValueAt(row, 3).toString();
        date_fin_txt.setText(table_click5);
        String table_click6 = jTable3.getModel().getValueAt(row, 4).toString();
        Type_sal2.setText(table_click6);
        String table_click3 = jTable3.getModel().getValueAt(row, 5).toString();
        lund1.setText(table_click3);
        String table_click7 = jTable3.getModel().getValueAt(row, 6).toString();
        ludS1.setText(table_click7);
        String table_click8 = jTable3.getModel().getValueAt(row, 7).toString();
        mard1.setText(table_click8);
        String table_click9 = jTable3.getModel().getValueAt(row, 8).toString();
        mardS1.setText(table_click9);
        String table_click10 = jTable3.getModel().getValueAt(row, 9).toString();
        merc1.setText(table_click10);
        String table_click11 = jTable3.getModel().getValueAt(row, 10).toString();
        MercS1.setText(table_click11);
        String table_click12 = jTable3.getModel().getValueAt(row, 11).toString();
        jeud1.setText(table_click12);

        String table_click13 = jTable3.getModel().getValueAt(row, 12).toString();
        jeudS1.setText(table_click13);
        String table_click14 = jTable3.getModel().getValueAt(row, 13).toString();
        vend1.setText(table_click14);
        String table_click15 = jTable3.getModel().getValueAt(row, 14).toString();
        VendS1.setText(table_click15);
        String table_click16 = jTable3.getModel().getValueAt(row, 15).toString();
        sam1.setText(table_click16);
        String table_click17 = jTable3.getModel().getValueAt(row, 16).toString();
        SamS1.setText(table_click17);
        String table_click18 = jTable3.getModel().getValueAt(row, 17).toString();
        dim1.setText(table_click18);
        String table_click19 = jTable3.getModel().getValueAt(row, 18).toString();
        dimS1.setText(table_click19);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void date_fin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_fin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_fin_txtActionPerformed

    private void date_deb_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_deb_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_deb_txtActionPerformed

    private void SamS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SamS1ActionPerformed

    private void dimS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimS1ActionPerformed

    private void sam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sam1ActionPerformed

    private void dim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dim1ActionPerformed

    private void AjouterEmploi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEmploi1ActionPerformed
 String  nom_user = nom_sal.getText();
        String date_deb_sem = dt_deb_sem1.getValue().toString();
        String date_fin_sem = dt_fin_sem1.getValue().toString();
        String type_user = Type_sal2.getText();
        String lundi = lund1.getText();
        String mardi = mard1.getText();
        String mercredi = merc1.getText();
        String jeudi = jeud1.getText();
        String vendredi = vend1.getText();
        String samedi = sam1.getText();
        String dimanche = dim1.getText();
        String lundiSoire = ludS1.getText();
        String mardiSoire = mardS1.getText();
        String mercrediSoire = MercS1.getText();
        String jeudiSoire = jeudS1.getText();
        String vendrediSoire = VendS1.getText();
        String samediSoire = SamS1.getText();
        String dimancheSoire = dimS1.getText();
         int ID =Integer.parseInt(Id_emploi.getText());

        Emploi emp = new Emploi();
        emp.setNom_user(nom_user);
        emp.setDate_deb_sem(date_deb_sem);
        emp.setDate_fin_sem(date_fin_sem);
        emp.setType_user(type_user);
        emp.setDimanche(dimanche);
        emp.getDimancheSoire();
        emp.setJeudi(jeudi);
        emp.setJeudiSoire(jeudiSoire);
        emp.setLundi(lundi);
        emp.setLundiSoire(lundiSoire);
        emp.setMardi(mardi);
        emp.setMardiSoire(mardiSoire);
        emp.setMercredi(mercredi);
        emp.setMercrediSoire(mercrediSoire);
        emp.setSamedi(samedi);
        emp.setSamediSoire(samediSoire);
        emp.setVendredi(vendredi);
        emp.setVendrediSoire(vendrediSoire);
        emp.setDimancheSoire(dimancheSoire);
        emp.setId_emploi(ID);

        GestionDeEmploiDuTemps empDAO = new GestionDeEmploiDuTemps();
        empDAO.ModifierEmploi(emp);
        JOptionPane.showMessageDialog(rootPane, "Modification effectueé"); // message d'alert
    }//GEN-LAST:event_AjouterEmploi1ActionPerformed

    private void ludS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ludS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ludS1ActionPerformed

    private void mardS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mardS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mardS1ActionPerformed

    private void MercS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MercS1ActionPerformed

    private void jeudS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeudS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeudS1ActionPerformed

    private void VendS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendS1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EnvoiMail e = new EnvoiMail();
        e.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jeud1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeud1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeud1ActionPerformed

    private void mard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mard1ActionPerformed

    private void vend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vend1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vend1ActionPerformed

    private void lund1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lund1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lund1ActionPerformed

    private void merc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merc1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        JOptionPane.showConfirmDialog(rootPane, "Etes vous sure de vouloir supprimer l'absence de Mr " + jTable3.getValueAt(jTable3.getSelectedRow(), 1) + "?", "",  JOptionPane.OK_CANCEL_OPTION);
 
    int ID =Integer.parseInt(Id_emploi.getText());

        Emploi emp = new Emploi();
        
      
        
        emp.setId_emploi(ID);

        GestionDeEmploiDuTemps empDAO = new GestionDeEmploiDuTemps();
        empDAO.SupprimerEmploi(emp);
//Afficher un message de confirmation
        JOptionPane.showMessageDialog(this, "Suppression effectué avec succès");

        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
jTable3 = new javax.swing.JTable();

jTable3.setModel(new DAO.graphics.TableEmploi());




jScrollPane3.setViewportView(jTable3);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeEmploi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeEmploi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeEmploi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeEmploi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeEmploi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterEmploi;
    private javax.swing.JButton AjouterEmploi1;
    private javax.swing.JTextField Id_emploi;
    private javax.swing.JTextField MercS;
    private javax.swing.JTextField MercS1;
    private javax.swing.JTextField SamS;
    private javax.swing.JTextField SamS1;
    private javax.swing.JTextField Type_sal2;
    private javax.swing.JTextField VendS;
    private javax.swing.JTextField VendS1;
    private javax.swing.JTextField cin_s;
    private javax.swing.JTextField date_deb_txt;
    private javax.swing.JTextField date_fin_txt;
    private javax.swing.JTextField dim;
    private javax.swing.JTextField dim1;
    private javax.swing.JTextField dimS;
    private javax.swing.JTextField dimS1;
    private javax.swing.JSpinner dt_deb_sem;
    private javax.swing.JSpinner dt_deb_sem1;
    private javax.swing.JSpinner dt_fin_sem;
    private javax.swing.JSpinner dt_fin_sem1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jeud;
    private javax.swing.JTextField jeud1;
    private javax.swing.JTextField jeudS;
    private javax.swing.JTextField jeudS1;
    private javax.swing.JTextField ludS;
    private javax.swing.JTextField ludS1;
    private javax.swing.JTextField lund;
    private javax.swing.JTextField lund1;
    private javax.swing.JTextField mard;
    private javax.swing.JTextField mard1;
    private javax.swing.JTextField mardS;
    private javax.swing.JTextField mardS1;
    private javax.swing.JTextField merc;
    private javax.swing.JTextField merc1;
    private javax.swing.JTextField nom_sal;
    private javax.swing.JTextField nom_sal2;
    private javax.swing.JTextField sam;
    private javax.swing.JTextField sam1;
    private javax.swing.JTextField type_sal1;
    private javax.swing.JTextField vend;
    private javax.swing.JTextField vend1;
    // End of variables declaration//GEN-END:variables
}
